### ISSUE TITLE
Doesn't work !!

### ISSUE THREAD

**Issue by BoomYo** [feasil/ComicDownloader#1]
I just tried with this URL and it does nothing when I click add button !

http://viewcomic.com/the-boys-omnibus-v1-001-2012/

![bug](https://cloud.githubusercontent.com/assets/22099224/21982876/a5cf4754-dbee-11e6-9bc7-b9176d97cc37.png)

**Comment by feasil** [comment]
The Exception thrown is just here for debug (when using a proxy).
Make sure the "lib" folder is next to ComicDownloader.jar (and contains the jsoup jar).

By the way, the following files have been updated : 
- ComicDownloader.jar (no more exception when no proxy used)
- howto.txt (note for the lib folder added)
