### ISSUE TITLE
Récupérer les index sur les sites

### ISSUE THREAD

**Issue by BoomYo** [feasil/ComicDownloader#2]
Il serait vraiment totalement génial de pouvoir sélectionner un site dans une liste, et que l'appli aille récupérer la liste de tous les titres disponibles.
Il suffirait dès lors de sélectionner celui voulu pour lancer le téléchargement.

**Comment by feasil** [comment]
Fonctionnalité disponible.
Le chargement de l'intégralité du catalogue est très long.
J'ai mâché le travail en intégrant un csv sous le dossier "list" (à placer à côté du jar).

L'update peut être fait via l'appli (nouvelle fenêtre disponible derrière le bouton "List comics" puis "Update").
Preview disponible en appuyant sur "Entrée" (ou en double cliquant sur un Tome).

Pour lancer le dl, il faut sélectionner un ou plusieurs comics (pas de tome) et cliquer sur le bouton en bas.
