### ISSUE TITLE
Avancement du téléchargement

### ISSUE THREAD

**Issue by BoomYo** [feasil/ComicDownloader#3]
Il serait vraiment extrêmement incroyable d'avoir une vue de l'état d'avancement et d'avoir la liste des téléchargements avancer automatiquement.

**Comment by feasil** [comment]
Cette fonctionnalité vraiment extrêmement incroyable est désormais disponible.
Ajout d'un scroll au démarrage des dl et d'un texte indiquant l'avancement.
